import type { ILLMSynthesizer } from './ILLMSynthesizer.js';
import type { GeneratedSection } from '@biotica/core';
import type { EvidenceSnapshot } from '@biotica/core';

/**
 * Stub implementation: returns deterministic placeholder text.
 * Replace with a real LLM client (e.g. OpenAI, Anthropic) that accepts
   * normalized evidence JSON and returns GeneratedSection with citations.
 */
export class StubLLMSynthesizer implements ILLMSynthesizer {
  async generateExecutiveSummary(_evidence: EvidenceSnapshot): Promise<GeneratedSection> {
    return {
      title: 'Executive summary',
      summary: 'This section is generated by an LLM synthesizer when enabled. Use a real implementation (e.g. OpenAI, Anthropic) with normalized evidence and citation rules.',
      evidence_points: ['Evidence points are populated from the evidence snapshot.'],
      inferences: ['Inferences must be clearly separated from factual evidence.'],
      risks: ['Risks are derived from evidence and commercial context.'],
      recommendations: ['Recommendations are for strategic use only.'],
      citations: ['Open Targets Platform', 'Report evidence snapshot'],
    };
  }

  async generateRisksAndRecommendations(_evidence: EvidenceSnapshot): Promise<GeneratedSection> {
    return {
      title: 'Risks and recommendations',
      summary: 'Stub placeholder. Replace with LLM that outputs structured risks and recommendations with citations.',
      evidence_points: [],
      inferences: [],
      risks: ['Evidence gaps', 'Competitive landscape uncertainty'],
      recommendations: ['Validate key assumptions with primary sources.'],
      citations: ['Evidence snapshot'],
    };
  }
}
